
# Assume Python 3.8
target-version = "py38"

[lint]
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "UP",          # pyupgrade
#  "N",           # pep8 naming
]

ignore = [
  "E501",   # Line too long
  "E722",   # Do not use bare 'except'
  "B904",   # Within an 'except' clause ...
]

unfixable = [
  "F841", # Removes unused variables
]

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "numpy"
