[tool.poetry]
name = "mapreader"
version = "0.1.1"
description = "A computer vision pipeline for the semantic exploration of maps/images at scale"
authors = ["kasra-hosseini <khosseini@turing.ac.uk>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "~3.8"
pytest = "^6.2.5"
geopy = "2.1.0"
matplotlib = "^3.5.0"
numpy = "^1.21.5"
pandas = "^1.3.4"
pyproj = "^3.3.0"
rasterio = "^1.2.10"
azure-storage-blob = "^12.9.0"
aiohttp = "^3.8.1"
Shapely = "^1.8.0"
nest-asyncio = "^1.5.1"
scikit-image = "^0.18.3"
scikit-learn = "^1.0.1"
torch = "^1.10.0"
torchvision = "^0.11.1"
jupyter = "^1.0.0"
ipykernel = "^6.5.1"
ipyannotate = "^0.1.0-beta.0"
keplergl = "^0.3.2"
Cython = "^0.29.24"
proj = "^0.2.0"
PyYAML = "^6.0"
simplekml = "^1.3.6"
tensorboard = "^2.7.0"
parhugin = "^0.0.3"
Fiona = "^1.8.21"
absl-py = "^1.0.0"
affine = "^2.3.0"
aiosignal = "^1.2.0"
appnope = "^0.1.2"
argon2-cffi-bindings = "^21.2.0"
argon2-cffi = "^21.3.0"
arrow = "^1.2.2"
asttokens = "^2.0.5"
async-timeout = "^4.0.2"
atomicwrites = "^1.4.0"
attrs = "^21.4.0"
azure-core = "^1.22.1"
backcall = "^0.2.0"
black = "^22.1.0"
bleach = "^4.1.0"
cachetools = "^5.0.0"
certifi = "^2021.10.8"
cffi = "^1.15.0"
charset-normalizer = "^2.0.12"
click-plugins = "^1.1.1"
click = "^8.0.3"
cligj = "^0.7.2"
colorama = "^0.4.4"
cryptography = "^36.0.1"
cycler = "^0.11.0"
debugpy = "^1.5.1"
decorator = "^5.1.1"
defusedxml = "^0.7.1"
entrypoints = "^0.4"
executing = "^0.8.2"
fonttools = "^4.29.1"
frozenlist = "^1.3.0"
geographiclib = "^1.52"
geopandas = "^0.10.2"
google-auth-oauthlib = "^0.4.6"
google-auth = "^2.6.0"
grpcio = "^1.43.0"
idna = "^3.3"
imageio = "^2.16.0"
importlib-metadata = "^4.11.1"
importlib-resources = "^5.4.0"
iniconfig = "^1.1.1"
ipython_genutils = "^0.2.0"
ipython = "^8.0.1"
ipywidgets = "^7.6.5"
isodate = "^0.6.1"
jedi = "^0.18.1"
Jinja2 = "^3.0.3"
joblib = "^1.1.0"
jsonschema = "^4.4.0"
jupyter-client = "^7.1.2"
jupyter-console = "^6.4.0"
jupyter-core = "^4.9.2"
jupyterlab-pygments = "^0.1.2"
jupyterlab-widgets = "^1.0.2"
kiwisolver = "^1.3.2"
Markdown = "^3.3.6"
MarkupSafe = "^2.0.1"
matplotlib-inline = "^0.1.3"
mistune = "^2.0.2"
msrest = "^0.6.21"
multidict = "^6.0.2"
munch = "^2.5.0"
mypy-extensions = "^0.4.3"
nbclient = "^0.5.11"
nbformat = "^5.1.3"
networkx = "^2.6.3"
notebook = "^6.4.8"
oauthlib = "^3.2.0"
packaging = "^21.3"
pandocfilters = "^1.5.0"
parso = "^0.8.3"
pathspec = "^0.9.0"
pexpect = "^4.8.0"
pickleshare = "^0.7.5"
Pillow = "^9.0.1"
platformdirs = "^2.5.0"
pluggy = "^1.0.0"
prometheus-client = "^0.13.1"
prompt-toolkit = "^3.0.28"
protobuf = "^3.19.4"
ptyprocess = "^0.7.0"
pure-eval = "^0.2.2"
py = "^1.11.0"
pyasn1-modules = "^0.2.8"
pyasn1 = "^0.4.8"
pycparser = "^2.21"
Pygments = "^2.11.2"
pyparsing = "^3.0.7"
pyrsistent = "^0.18.1"
python-dateutil = "^2.8.2"
pytz = "^2021.3"
PyWavelets = "^1.2.0"
pyzmq = "^22.3.0"
qtconsole = "^5.2.2"
QtPy = "^2.0.1"
requests-oauthlib = "^1.3.1"
requests = "^2.27.1"
rsa = "^4.8"
scipy = "^1.8.0"
Send2Trash = "^1.8.0"
setuptools-scm = "^6.4.2"
six = "^1.16.0"
snuggs = "^1.4.7"
stack-data = "^0.2.0"
tensorboard-data-server = "^0.6.1"
tensorboard-plugin-wit = "^1.8.1"
terminado = "^0.13.1"
tifffile = "^2022.2.9"
toml = "^0.10.2"
tomli = "^2.0.1"
tornado = "^6.1"
traitlets = "^5.1.1"
traittypes = "^0.2.1"
typing-extensions = "^4.1.1"
urllib3 = "^1.26.8"
wcwidth = "^0.2.5"
webencodings = "^0.5.1"
Werkzeug = "^2.0.3"
widgetsnbextension = "^3.5.2"
yarl = "^1.7.2"
zipp = "^3.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
