[tool.poetry]
name = "mapreader"
version = "0.1.1"
description = "A computer vision pipeline for the semantic exploration of maps/images at scale"
authors = ["kasra-hosseini <khosseini@turing.ac.uk>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "~3.8"
pytest = "^6.2.5"
geopy = "2.1.0"
matplotlib = "^3.5.0"
numpy = "^1.21.5"
pandas = "^1.3.4"
pyproj = "^3.2.0"
rasterio = "^1.2.10"
azure-storage-blob = "^12.9.0"
aiohttp = "^3.8.1"
Shapely = "^1.8.0"
nest-asyncio = "^1.5.1"
scikit-image = "^0.18.3"
scikit-learn = "^1.0.1"
torch = "^1.10.0"
torchvision = "^0.11.1"
jupyter = "^1.0.0"
ipykernel = "^6.5.1"
ipyannotate = "^0.1.0-beta.0"
keplergl = "^0.3.2"
Cython = "^0.29.24"
proj = "^0.2.0"
PyYAML = "^6.0"
simplekml = "^1.3.6"
tensorboard = "^2.7.0"
parhugin = "^0.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
