---
name: Units Tests - Text Spotting

on: [push]

# Run linter with github actions for quick feedbacks.
jobs:

  macos_tests:
    runs-on: macos-latest
    # run on PRs, or commits to facebookresearch (not internal)
    strategy:
      fail-fast: false
      matrix:
        torch: ["1.13.1", "2.2.2"]
        include:
          - torch: "1.13.1"
            torchvision: "0.14.1"
          - torch: "2.2.2"
            torchvision: "0.17.2"
        python-version: ["3.9", "3.12"]
    env:
      # point datasets to ~/.torch so it's cached by CI
      DETECTRON2_DATASETS: ~/.torch/datasets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}/lib/${{ matrix.python-version }}/site-packages
            ~/.torch
          key: ${{ runner.os }}-torch${{ matrix.torch }}-${{ hashFiles('setup.py') }}-20220119

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install wheel ninja opencv-python-headless onnx pytest-xdist
          python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
          # install from github to get latest; install iopath first since fvcore depends on it
          python -m pip install -U 'git+https://github.com/facebookresearch/iopath'
          python -m pip install -U 'git+https://github.com/facebookresearch/fvcore'
          wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
          python collect_env.py

      - name: Build and install
        run: |
          CC=clang CXX=clang++ python -m pip install -e 'git+https://github.com/facebookresearch/detectron2.git'
          python -m detectron2.utils.collect_env
          python -m pip install 'git+https://github.com/maps-as-data/DPText-DETR.git' # Install DPText-DETR

      - name: Run unittests
        run: python -m pytest tests/test_text_spotting/
