# Adapted from https://github.com/alan-turing-institute/scivision/blob/main/.github/workflows/publish-to-pypi.yml
name: Publish all Python 🐍 distributions 📦 to Test PyPI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  build-and-publish:
    name: Publish all Python 🐍 distributions 📦 to Test PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build --user
    # - name: Create build version number for development builds
    #   if: ${{ ! startsWith(github.ref, 'refs/tags') }}
    #   run: |
    #     poetry version `poetry version -s``echo -alpha.`${{ github.run_number }}
    - name: Build a binary wheel and a source tarball
      run: |
        python3 -m build --sdist --wheel --outdir dist/
    - name: Publish all builds to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true