
name: Publish to Conda Forge

on: [push]

jobs:

  build_conda:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-22.04]
        python-version: [3.8]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all history so that versioneer can determine the version number
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Taken from https://github.com/actions/starter-workflows/blob/28a47a7bc4497d7b0c039030a1eba04556bf9a64/ci/python-package-conda.yml#L17
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install conda-build tools
        run: |
          conda install conda-build
          conda install conda-verify
          conda install conda-package-handling

      - name: Create local Conda channel
        run: |
          mkdir -p ./conda-bld
          mkdir -p ./conda_tar_gz_bld
          conda index ./conda-bld

      - name: Build dependencies
        run: |
          conda-build ./conda/parhugin/conda/meta.yaml --output-folder ./conda-bld
          cph transmute  --out-folder ./conda-bld ./conda-bld/noarch/parhugin-*.tar.bz2 .conda
          conda-build ./conda/ipyannotate/conda/meta.yaml --output-folder ./conda-bld
          cph transmute  --out-folder ./conda-bld ./conda-bld/noarch/ipyannotate-*.tar.bz2 .conda


      - name: Upload dependencies
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload ./conda-bld/noarch/*.conda


      # - name: Build package
      #   run: |
      #     conda-build -c conda-forge -c ./conda-bld ./conda/
